### ISSUE TITLE
Halos Broken - P9 Headless

### ISSUE THREAD

**Issue by seandenigris** [pharo-project/pharo-vm#100]
Morphic halos don't seem to be working with the Pharo 9 headless VM. They
seem fine with headful.

Still a bug as of Pharo-9.0.0+build.572.sha.308d3ba56ee06f02c3d3f916da5636d04ceca15b (64 Bit)
Mac OS 10.14.6

**Comment by tesonep** [comment]
This is a problem in the image side. As the SDL events should emulate the ALT+LeftButton as MiddleButton
Fixed in https://github.com/pharo-project/pharo/pull/7044
