### ISSUE TITLE
pharo-vm crashes after pushing commints with iceberg and without authentication

### ISSUE THREAD

**Issue by jordanmontt** [pharo-project/pharo-vm#118]
If you download a new Pharo 9 image and clone a git repo into it. Make some changes, commit them, and then you try to push them, the vm crashes. I am using Window 10.

This error is shown: 

![image](https://user-images.githubusercontent.com/33934979/98444457-b3ce5c00-2109-11eb-89e1-46acb6c50864.png)

**Comment by astares** [comment]
Same on Ubuntu

Downloading the latest 90 Image:
    http://files.pharo.org/get-files/90/pharo64.zip
Pharo.image
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/90/pharo64-linux-stable.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
pharo: /home/travis/build/pharo-project/opensmalltalk-vm/build.linux64x64/third-party/libgit2-0.25.1/src/transports/http.c:377: on_headers_complete: Assertion `t->cred' failed.
./pharo-ui: line 11: 13384 Aborted                 (core dumped) "$DIR"/"pharo-vm/pharo" "$@"


<blockquote></blockquote>
<blockquote></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/19434631?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732">Release r3732 · OpenSmalltalk/opensmalltalk-vm</a></strong></div><div>N.B. For Squeak/Pharo/Croquet please use the archives whose names begin with
Cog or cog.  The archives whose names begin with nsvm or Newspeak are
for Newspeak and are missing plugins required by S...</div></blockquote>
