### ISSUE TITLE
F2 VM debug options are not present anymore

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-project/pharo-vm#125]
And it is quite useful to be able to spot the error that hangs the VM especially when OUPS do not work.
Is there any plan to add them back or to access them from another way?

Current menu:
![image](https://user-images.githubusercontent.com/4706329/99783532-d190bd80-2b1a-11eb-9a99-5eae05c51947.png)

Old menu:
![image](https://user-images.githubusercontent.com/4706329/99783421-b2922b80-2b1a-11eb-8473-02feabf78f5d.png)

Would have help to debug https://github.com/pharo-project/pharo/issues/7782

**Comment by astares** [comment]
Yes - that menu is sometimes useful. 

Maybe the menu entry could only be enabled only when a special INI setting or other is provided. If you build a customized app 
you might not want to have that Squeak/Pharo VM specific menu (by default) for the end users/customer.

Also (for Windows) it would be good if (via one of the options) the trace  could be streamed to the **internal windows debug output** using the OutputDebugStringA/OutputDebugStringW API of Windows.

https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw

They can be made visible via regular debugging tools like:
 - dbmon.exe from the SDK
 - https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
 - https://www.codeproject.com/Articles/13345/DbMon-NET-A-simple-NET-OutputDebugString-capturer
 and other

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw">OutputDebugStringW function (debugapi.h) - Win32 apps</a></strong></div><div>Sends a string to the debugger for display.</div></blockquote>
<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/sysinternals/downloads/debugview">DebugView - Windows Sysinternals</a></strong></div><div>This program intercepts calls made to DbgPrint by device drivers and OutputDebugString made by Win32 programs.</div></blockquote>
<blockquote><img src="https://www.codeproject.com/KB/trace/DbMonNET/Thumb-13345.gif" width="48" align="right"><div><strong><a href="https://www.codeproject.com/Articles/13345/DbMon-NET-A-simple-NET-OutputDebugString-capturer">DbMon.NET - A simple .NET OutputDebugString capturer</a></strong></div><div>A .NET port of the VC++ 6.0 sample, 'dbmon'.</div></blockquote>

**Comment by StevenCostiou** [comment]
hi @VincentBlondeau could you give me the cases in which OUPS does not work?
I need that as a starting point to investigate, at least a reproducible case.

**Comment by VincentBlondeau** [comment]
The case here is to not crash the current process stack in the PharoDebug.log. It is insufficient if someone want further debugging. A full dump will be required. What is providing the F2 command was great for this.

@tesonep told me that in the new VM, there is a possibility to send a signal to the process to dump the current state. I was looking for a command to send a signal to a Windows running process from a cmd. But I didn't find anything. Do you know how to do?

**Comment by astares** [comment]
@VincentBlondeau either try a regular
```
taskkill /f -im Pharo.exe
```
or use additional tools like https://github.com/alirdn/windows-kill

<blockquote><img src="https://avatars2.githubusercontent.com/u/13997186?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/alirdn/windows-kill">alirdn/windows-kill</a></strong></div><div>Send signal to process by PID in Windows, like POSIX kill - alirdn/windows-kill</div></blockquote>

**Comment by VincentBlondeau** [comment]
@astares I tried with the tool you suggested, the image is killed but no debug trace is left (checked in VM and image folders) with a SIGBREAK.

**Comment by VincentBlondeau** [comment]
This issue need to be fixed! We cannot debug properly zombie/frozen images.
Tried today:
taskkill /IM Pharo.exe -> image still open and frozen, no log / dump generated

**Comment by fedemennite** [comment]
taskkill can just be used to actually terminate a process AFAIK.
Another viable option would be for the VM to have a C function that would dump the stacks, that can be called by an attached windows debugger.
Some function like that is probably already there as it's being called by OS signal process handling on linux/MacOS.

**Comment by VincentBlondeau** [comment]
Option added and working:
![image](https://user-images.githubusercontent.com/4706329/137096043-62b0b5c6-11d4-4a76-a7e8-8d9ec29c0348.png)
