### ISSUE TITLE
Latest Linux VM can't handle -vm-display-null

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-vm#15]
https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/421

On Linux (Debian 10, Ubuntu 14.04.5) curl get.pharo.org/64/vmLatest80 | bash; ./pharo fails with
could not find module vm-display-null

Just to flesh this out, try ./pharo -nodisplay

**Comment by LucFabresse** [comment]
old. should be closed.
