### ISSUE TITLE
VM crash on a #become: performed on a ByteArray istance that was just allocated

### ISSUE THREAD

**Issue by fedemennite** [pharo-project/pharo-vm#156]
To reproduce the crash please evalute the code below in a vanilla Pharo 9.0 image:
`	| newBytes bytes  |
	bytes := ByteArray new.
	newBytes := ByteArray new: 23257379.
	newBytes
		replaceFrom: 1
		to: 0
		with: bytes
		startingAt: 1.
	bytes become: newBytes`

There seems to be some correlation with the current size of the memory heap and the potential need to growth it by allocating headroom space.
Apparently if the allocated ByteArray size is larger than the half of size of the configured growth headroom, the machine ends up crashing.

**Comment by tesonep** [comment]
Fixed in #161
