### ISSUE TITLE
Ubuntu 20.04 cmake

### ISSUE THREAD

**Issue by sbragagnolo** [pharo-project/pharo-vm#169]
Attempting to build the VM in ubuntu 20.04: 

 Install all the documented dependencies. 

 git clone git@github.com:pharo-project/opensmalltalk-vm.git
 cd opensmalltalk-vm
 cmake . 

...
CMake Error at SDL2-src/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there

-- Configuring incomplete, errors occurred!
See also "/home/sor/opensmalltalk-vm/CMakeFiles/CMakeOutput.log".
See also "/home/sor/opensmalltalk-vm/CMakeFiles/CMakeError.log".

I did as the error asks: 
cd SDL2-src
mkdir build
cd build
cmake ..

I still having the same error. 

I tried with derivatives of the same proposal, but all of them gave me the same error .

Not sure if there is a lack on the documentation, or i found a bug. Any lead?

**Comment by guillep** [comment]
You should *never* do an in-tree build, so it is validated :)

The idea is that you don’t do the build in the same directory of your repository, to avoid making it dirty (and then committing wrong things, and stuff…).
The contrary of an in-tree build is an out of source build, for example in a directory called build:

```bash
git clone git@github.com <mailto:git@github.com>:pharo-project/opensmalltalk-vm.git
cmake -S opensmalltalk-vm -B build
```

**Comment by sbragagnolo** [comment]
Good. I just made it work be using the jenkins way: 
cmake -G "Unix Makefiles" -DFLAVOUR=CoInterpreter -DPHARO_DEPENDENCIES_PREFER_DOWNLOAD_BINARIES=TRUE
i tried with the flag on false and it did not work ofc. 
Maybe it would be nice to add it to the documentation.
By the time been i am just going to change the readme to do as you said, it seems to work better (not completely, since i had an error, but it seems unrelated with thieone,  so i am closing this. )

**Comment by guillep** [comment]
> Good. I just made it work be using the jenkins way:
> cmake -G "Unix Makefiles" -DFLAVOUR=CoInterpreter -DPHARO_DEPENDENCIES_PREFER_DOWNLOAD_BINARIES=TRUE
> i tried with the flag on false and it did not work ofc.

Could you tell what did not work?
