### ISSUE TITLE
OSSUnixSubprocess fails when redirecting stdio

### ISSUE THREAD

**Issue by akgrant43** [pharo-project/pharo-vm#233]
OSSUnixSubprocess fails on linux and Mac (not tested on Windows) (seemingly) randomly due to incompatible integer representations in the VM (StackInterpeter) and FilePlugin and UnixOSProcessPlugin.  The VM (StackInterpreter) stores the globalSessionID as a sqInt (signed 64 bit integer), while FilePlugin stores the session ID as an int (signed 32 bit integer).  FilePlugin happens to compare the values in such a way that if the globalSessionID is greater than 0x7FFFFFF the comparison succeeds, while UnixOSProcessPlugin doesn't.

The result is that any attempt to use OSSUnixSubprocess and redirect stdio will fail if the globalSessionID is 32 bits or larger, e.g.:

```
OSSUnixSubprocess new
    command: 'ls';
    redirectStdout;
       run.
```

There are a few possible solutions:

1. Extend SQFile.sessionID to be 64 bits, so that it matches the VM.  This data structure is copied in to the VM as a ByteArray, so will increase memory usage a little, but there may also be code that makes assumptions about the size and / or offsets of the structure.
2. Modify UnixOSProcessPlugin to do the comparison in a safe way.  This should be straightforward, but I haven't found the slang code yet, and there may be other places that make the same mistake.
3. Modify globalSessionID so that it never uses more than 31 bits.

The last option seems the safest to me. 

- In practice, globalSessionID has only used 31 bits most of the time up to now. 
- This protects any other code that makes assumptions about the size of the globalSessionID.
- The chances of a collision based on simple statistics are around 1 in 2 billion.  In practice it requires an image to be started, saved and restarted and have an open file which is illegally accessed in the second session, which is probably significantly less than 1 in 2 billion.
The required change is in StackInterpreter>>initializeInterpreter::

```
    [globalSessionID = 0] whileTrue:
        [globalSessionID := self
            cCode: [((self time: #NULL) + self ioMSecs) bitAnd: 16r7FFFFFFF]
            inSmalltalk: [(Random new next * (SmallInteger maxVal min: 16r7FFFFFFF)) asInteger]].
```

adding bitAnd: 16r7FFFFFFF.

**Comment by guillep** [comment]
This was fixed in #248
