### ISSUE TITLE
Crash while filing in large code base

### ISSUE THREAD

**Issue by fedemennite** [pharo-project/pharo-vm#256]
The get the VM crashing when importing a large code base in a vanilla pharo 9 image.
Attaching stacks. [vmstacks.txt](https://github.com/pharo-project/opensmalltalk-vm/files/6585542/vmstacks.txt)
I can provide the Windows dmp file on demand.

**Comment by fedemennite** [comment]
FYI. This doesn't seem to be happening anymore.

**Comment by guillep** [comment]
Thanks! I'll close it for now, please, do not hesitate to re-open/flag it if it happens again.

Cheers
