### ISSUE TITLE
Would be good to centralize the dependent packages

### ISSUE THREAD

**Issue by Ducasse** [pharo-project/pharo-vm#3]
"Dependencies from other repositories"
			spec
				package: 'SharedPool-Speech' with: [
					spec repository: 'http://www.squeaksource.com/Speech' ];
				package: 'MethodMassage' with: [
					spec repository: 'http://ss3.gemstone.com/ss/MethodMassage' ];
				package: 'MethodMassageCompatibility' with: [
					spec repository: 'http://ss3.gemstone.com/ss/MethodMassage' ];
				package: 'Printf' with: [
					spec repository: 'http://www.squeaksource.com/Printf' ].

**Comment by Ducasse** [comment]
Normally since the KlattPlugin is removed the Speech dependency is not mandatory anymore.

**Comment by LucFabresse** [comment]
should be closed?

**Comment by hernanmd** [comment]
I couldn't find any references to squeaksource in the pharo-vm BaslineOfVMMaker in [active branches](https://github.com/pharo-project/pharo-vm/branches):

- Printf is loaded from pharo-vm.
- KlattPlugin / Speech are not referenced
- MethodMassage not referenced anymore, I read in the description of MethodMassage: "A small set of tools centered around bytecode method disassembly and reassembly. The system can duplicate all methods in the system, via method -> disassembly -> assembly -> duplicate method. The disassembler is used to implement basic block coverage by replacing the first bytecode of every basic block with an illegal bytecode which causes an exception when first executed (needs an up-to-date Cog VM)." Is that replaced by [pharo-llvmDisassembler](https://github.com/pharo-project/pharo-llvmDisassembler) @guillep ?
- Note that squeaksource reference are present in other [stale branches](https://github.com/pharo-project/pharo-vm/branches/stale): 
-- https://github.com/pharo-project/pharo-vm/blob/feat%2Fcogmt/smalltalksrc/BaselineOfVMMaker/BaselineOfVMMaker.class.st
-- https://github.com/pharo-project/pharo-vm/blob/feat%2Flive-typing-stack/smalltalksrc/BaselineOfVMMaker/BaselineOfVMMaker.class.st




<blockquote><img src="https://opengraph.githubassets.com/21e31ac830c1130732d7b9f0baede0c78fa445d2346d0033cffa8a168cb572cb/pharo-project/pharo-vm" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm">pharo-vm/BaselineOfVMMaker.class.st at feat/cogmt · pharo-project/pharo-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/pharo-vm development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/21e31ac830c1130732d7b9f0baede0c78fa445d2346d0033cffa8a168cb572cb/pharo-project/pharo-vm" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm">pharo-vm/BaselineOfVMMaker.class.st at feat/live-typing-stack · pharo-project/pharo-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/pharo-vm development by creating an account on GitHub.</div></blockquote>

**Comment by noha** [comment]
I opt for closing this

**Comment by guillep** [comment]
yes, very old
