### ISSUE TITLE
Remove pkgconfig directory from Mac plugins

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-vm#340]
In the mac VM http://files.pharo.org/get-files/90/pharo64-mac-stable.zip, there is a strange file: `Pharo.app/Contents/MacOS/Plugins/pkgconfig/`. It breaks the signing. 
The pkgconfig file is empty and should be removed

**Comment by tesonep** [comment]
Ok, I will check it

**Comment by tesonep** [comment]
Hi @demarey the correct downloads to use should include the OS + Architecture, for OSX they are:

- http://files.pharo.org/get-files/90/pharo-vm-Darwin-arm64-stable.zip
- http://files.pharo.org/get-files/90/pharo-vm-Darwin-x86_64-stable.zip

That is an old version. Is the launcher using these new locations? I think we have changed that.

Cheers,
Pablo

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by demarey** [comment]
@tesonep Pharo Launcher uses new locations. But Pharo Launcher build relies on pharo-build-script that still use old URLs: https://github.com/pharo-project/pharo-build-scripts/blob/9c8cb3c898b514122f5785068f458cc6248179e3/build-platform.sh#L264 
This kind of URL change has a lot of hidden impacts. I will check to update these scripts. Thanks

<blockquote><img src="https://opengraph.githubassets.com/a1c86ca3dcda01af3258a22b0fc2f343211ad25e4fcc57f6789153b62d6ee044/pharo-project/pharo-build-scripts" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-build-scripts">pharo-build-scripts/build-platform.sh at 9c8cb3c898b514122f5785068f458cc6248179e3 · pharo-project/pharo-build-scripts</a></strong></div><div>Scripts for building pharo distributions. Contribute to pharo-project/pharo-build-scripts development by creating an account on GitHub.</div></blockquote>
