### ISSUE TITLE
VM build fails when using C-reserved words as temp variable names

### ISSUE THREAD

**Issue by nrainhart** [pharo-project/pharo-vm#429]
While working on bytecode operations (see `initializeBytecodeTableForSistaV1`), I used `register` as a temp variable name in one of the bytecode handlers.

At the moment of building the VM, I got a parse error, as `register` is a reserved word in C.

I think we should detect those cases, and add a prefix/suffix to those variable names so that they do not collide with C reserved words.

**Comment by PalumboN** [comment]
https://github.com/pharo-project/pharo-vm/pull/607#discussion_r1218012898

**Comment by PalumboN** [comment]
@ivojawer we can close this, right?

**Comment by ivojawer** [comment]
Yes!

**Comment by guillep** [comment]
Merci @ivojawer bo cú
