### ISSUE TITLE
Windows VM Pharo11: can we get update of Cairo and FreeType2

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-vm#466]
If one checks https://github.com/pharo-graphics/Alexandrie
it is mentioned that it had been tested with 

- Cairo 1.16.0
- FreeType 2.12.1

If one grabs latest Pharo Windows VM using Launcher one gets elder versions:

![image](https://user-images.githubusercontent.com/5980033/193070334-5952a90f-b6c4-4b42-8758-913acb64d02c.png)

Can we get an update of these two libraries for the Pharo11 VM?

**Comment by demarey** [comment]
I close the issue since Pharo 11 VM is now in version 10.0.9 with the following dependencies:
- `CairoLibrary uniqueInstance versionString.` "'1.17.4'"
- `FT2Library current libraryVersion` "2.12.1"
