### ISSUE TITLE
UUIDPlugin.dll is put into quarantine

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-vm#526]
Users are reporting that Pharo is put into quarantine on Windows by some virus software. Reason seem to be the UUIDPlugin.dll

(see https://discord.com/channels/223421264751099906/916030520134107177/1047091636255068212)

![image](https://user-images.githubusercontent.com/5980033/210724054-2dc9b895-7019-46c2-8363-3938fb7a6383.png)

![image](https://user-images.githubusercontent.com/5980033/210724127-044a697a-649c-44c7-a2fa-74c44b8bde4e.png)

https://www.virustotal.com/gui/file/83ea83b85cfb7ee71abc6f161265b819e6447d97c34b72fbedde99dd75c24f2e

https://www.virustotal.com/gui/file/b09f4f98766474d8f57d4a5e937f482e9ef4154a990fd4b2e7dae5a5057dfc2e

As we want Pharo to be used in companies and this might reduce their trust when a security issue already pops up right in the beginning this is not good.

Is there something that could be done from VM building side to improve the situation? Maybe it is possible that the code is changed so the DLL is not not recognized with the current byte order as a virus....

**Comment by Robenroute** [comment]
Confirmed; Bitdefender Total Security Build 26.0.33.139 on Windows 11. UUIDPlugin.dll infected with Trojan.GenericKD.65337840.

**Comment by tesonep** [comment]
Fixed in upstream

**Comment by astares** [comment]
@tesonep can you please give more insights where the fix is or how it has been fixed?
