### ISSUE TITLE
Links in README lead to nowhere

### ISSUE THREAD

**Issue by astares** [pharo-project/pharo-vm#541]
Visit https://github.com/pharo-project/pharo-vm
and click on "Flavors" and you end in non-existing page

https://github.com/pharo-project/pharo-vm/blob/pharo-10/Flavors

![image](https://user-images.githubusercontent.com/5980033/221999139-1af7c458-239d-4127-a435-888307bf6ff7.png)

**Comment by AbhinavMir** [comment]
FIFY :-) let me know if this looks good @astares 

https://github.com/pharo-project/pharo-vm/pull/542

**Comment by astares** [comment]
@AbhinavMir Great thanks!
