### ISSUE TITLE
Updates for plugin generation

### ISSUE THREAD

**Issue by hernanmd** [pharo-project/pharo-vm#551]
To succesfully generate a plugin the following code could be run:

```smalltalk
(PharoVMMaker
	on: CoInterpreter
	outputDirectory: 'src' asFileReference)
	internal: #(  ) external: #( MyPlugin );
	generateExternalPlugins.
```

However the following methods should remove references to make it work according to latest updates in pharo-10

`PharoVMMaker>>vmMakerWith:memoryManager:` : Contains a reference to #COGMTVM which is not used anymore.
`StackInterpreter class>>initializeBytecodeTable` : Contains a reference to #bytecodeTableInitializer which is not used anymore.

**Comment by hernanmd** [comment]
Merged in https://github.com/pharo-project/pharo-vm/blob/9fefc3a85135b02ea7bede068285f1d87bc9df5d/smalltalksrc/VMMakerCompatibilityForPharo6/PharoVMMaker.class.st#L210

**Comment by guillep** [comment]
Thanks! :)
