### ISSUE TITLE
LibSDL2 not found in newer macOS arm64

### ISSUE THREAD

**Issue by hernanmd** [pharo-project/pharo-vm#553]
According to https://docs.brew.sh/Installation, HOMEBREW_PREFIX was changed to a new default location: /opt/homebrew, value which can be found executing: `brew config`.

To keep updated FindSDL2.cmake should include the following directories for arm64:

  - /opt/homebrew/lib/
  - /opt/homebrew/opt/

And for intel:

  - /usr/local/lib/
  - /usr/local/opt/

**Comment by guillep** [comment]
Yes!

**Comment by hernanmd** [comment]
I've been hunting the problem why libSDL2 was not copied automatically if found in the target system. 

There are two issues:

1) It is strange that after the function find_system_SDL2(), if found, nothing is done with it. My system contains libSDL2 already installed and I expected it to be copied to the Plugins directory. So for this I add a copy command to importSDL2.cmake:

```cmake
    ...
    if(NOT SDL2_FOUND)
      # Only build SDL if we are in MSVC, otherwise, download
      if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(SHOULD_BUILD_SDL FALSE)
      else()
        set(SHOULD_BUILD_SDL TRUE)
      endif()
      if (SHOULD_BUILD_SDL)
        build_SDL2()
      else()
        download_SDL2()
      endif()
    else()
      # copy
      message(STATUS "Copying system libSDL2-2.0")
      add_custom_target(SDL2_copy
			  COMMAND ${CMAKE_COMMAND} -E create_symlink libSDL2-2.0.dylib PARENT_SCOPE
      )
```
And it was copied, but this wasn't enough.

2) The current search path order raise a problem for users which have migrated from Intel Macs to ARM Macs: libraries like libSDL2 are not deleted automatically. 

So if the search order is this:

```cmake
SET(SDL2_SEARCH_PATHS
	~/Library/Frameworks
	/Library/Frameworks
	/usr/local
	/usr
	/sw # Fink
	/opt/local # DarwinPorts
	/opt/homebrew/lib
	/opt/csw # Blastwave
	/opt
	${SDL2_PATH}
)
```

then SDL2 libraries for x86_64 will be found first (because they're located under /usr/local), and used, instead of the corresponding to ARM which are now under /opt/homebrew. 

So the user should delete manually x86_64 libraries in all possible locations before the ARM ones, or we could try to detect the right library to copy. I'd like to read suggestions.

**Comment by hernanmd** [comment]
WiP: https://github.com/pharo-project/pharo-vm/compare/pharo-10...hernanmd:pharo-vm:update_find_sdl2?expand=1

<blockquote><img src="https://opengraph.githubassets.com/720b0450d86899a5c1cfefb6284899ec4caa99dd26bcecb39f1fef18dcb55dfa/pharo-project/pharo-vm" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm">Comparing pharo-project:pharo-10...hernanmd:update_find_sdl2 · pharo-project/pharo-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/pharo-vm development by creating an account on GitHub.</div></blockquote>

**Comment by guillep** [comment]
I don't think the vm build should account for having x86 libraries in your ARM system.
That is a very corner case.

Otherwise, we should also manage the build for a buggy C compiler? I don't think so...

**Comment by hernanmd** [comment]
Ok, thanks!

**Comment by guillep** [comment]
Just for documentation purposes, this issue is partially fixed in https://github.com/pharo-project/pharo-vm/pull/555
