### ISSUE TITLE
Add a parameter to ignore plist file on OS X

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-vm#597]
Currently, the VM always read the plist file on OS X and it is then impossible to override some of the default values.
See https://github.com/pharo-project/pharo-vm/blob/pharo-10/src/parameters/parameters.c#L659
One solution would be to add an option to ignore the reading of default parameters from the plist file (or have a way to override them). It would allow to "reuse" the VM shipped in a Pharo app for a slightly different purpose.

**Comment by guillep** [comment]
My understanding is that the default values are read from the plist file, but then the command line argument are read AFTER and can override them:

```c
#ifdef __APPLE__
	//If it is OSX I read parameters from the PList
	fillParametersFromPList(parameters);
#endif

	// Split the argument vector in two separate vectors.
	VMErrorCode error = splitVMAndImageParameters(argc, argv, parameters);
```

Or I don't understand the issue, or the issue is somewhere else :)

**Comment by demarey** [comment]
From what I experienced, by example, it was impossible to run an image in headless mode from command line.

ex:
```bash
/Applications/PharoLauncher.app/Contents/MacOS/Pharo --args --headless ~/Documents/Pharo/images/Pharo10/Pharo10.image
```

**Comment by guillep** [comment]
Ok, so the problem is not in the line you pointed out!! What seems to happen is that the default image is taken from the plist, and if the image is set, the headless/parameter is not read from command line:

https://github.com/pharo-project/pharo-vm/blob/bec2f79d69c1532a39dcd3a5a038c32075093a8e/src/parameters/parameters.c#L281

**Comment by demarey** [comment]
yes, the idea to ignore the plist file was the easiest one and could sometime be useful (when you do not know what are the defaults).
What could work is to read defaults from plist file, and allow to override them on command line, and keep the same behaviour as if args were given directly on command line and no plist file.
