### ISSUE TITLE
fgrep is obsolescent

### ISSUE THREAD

**Issue by LucFabresse** [pharo-project/pharo-vm#608]
```bash
./pharo ~/Pharo/images/Pharo\ 12.0/Pharo\ 12.0.image
fgrep: warning: fgrep is obsolescent; using grep -F
```

**Comment by LucFabresse** [comment]
arg, I did a mistake and the commit directly went into pharo-12 branch instead of a pull request...
https://github.com/pharo-project/pharo-vm/commit/8adb840f485d74307fc49db61d3e60aa113db05d

**Comment by demarey** [comment]
shouldn't this issue be closed?

**Comment by LucFabresse** [comment]
Yes thx
