### ISSUE TITLE
Pharo 11 VM 10.0.7 is Crashing on Windows 11

### ISSUE THREAD

**Issue by vitormcruz** [pharo-project/pharo-vm#704]
Originally I created this issue on https://github.com/pharo-project/pharo/issues/14956, but I believe this might be a problem with the VM. I got the following error upon image opening:

`qMakeMemoryNotExecutableFromTo (extracted/vm/src/win/sqWin32SpurAlloc.c:226):VirtualProtect(x,y,PAGE_EXECUTE_READWRITE): No error`

When loading a project with Iceberg, the Vm crashes. The debug log is attached, the error is:

> EXCEPTION_ACCESS_VIOLATION(-1073741819) at 0x000000006fb7d470 - 2023-10-13 15:20:35.835

[pharo-16692.log](https://github.com/pharo-project/pharo/files/12897444/pharo-16692.log)

**Comment by guillep** [comment]
Hi @vitormcruz ! Could you share the build of the image you are using? You can access it in the Help>about menu.

I'm looking for the string that looks like:

```
Pharo 12.0.0
Build information: Pharo-12.0.0+build.884.sha.80186f76f15ac0fad8396f4092c371a264a7189f (64 Bit)
```

Thanks for the report!

**Comment by vitormcruz** [comment]
Hello. 

Pharo 11.0.0
Build information: Pharo-11.0.0+build.707.sha.f720787cab0b25f0a8a811d66f2a8d3633ad8ba3 (64 Bit)

**Comment by vitormcruz** [comment]
I tried to update the image version — it is not clear to me how I can discover when there is a new version available, or if it is stable or not — so I just created a new one from Launcher, and it brought a new one:

Pharo 11.0.0
Build information: Pharo-11.0.0+build.710.sha.ea28d8552cac85a7ce1e9c34ab1e7bd45f7b9910 (64 Bit)

This one didn't crash, but a Tonel error happened: "Can't parse method body" and I am not sure this prompted after or before the point where the image was crashing. But debugging logs shows even more problems, like:

[DEBUG] 2023-10-17 14:45:31.000 loadModuleHandle (src/externalPrimitives.c:170):Try loading  DSAPrims

and:

[WARN ] 2023-10-17 14:46:45.000 getModuleSymbol (src/externalPrimitives.c:198):Retrying in VM DLL (lots of this)

not sure if those are relevant.

**Comment by vitormcruz** [comment]
I fixed the tonel problem and the image is working correctly now, no more crashing. I will test i more and see if the problem don't happen again (but the errors and warnings are still reported on the debug logs)

**Comment by jordanmontt** [comment]
Hello,
What was the tonel problem?

**Comment by vitormcruz** [comment]
The Tonel problem was my mistake, it is related to this: https://github.com/pharo-project/pharo/issues/14569, I was trying to fix and generated malformed st files.

**Comment by guillep** [comment]
Oh, sorry for coming back so late, I was travelling all week.

It's good news that the problem seems to be solved.
Indeed, the latest versions of the VM require the latest versions of the image, the ephemeron changes were too disruptive.
I'd like to enforce that somehow (or notify the user of potential incompatibilities). => It would be nice to have some help here...

Do you care if I close the issue? We can re-open it later if required.
