### ISSUE TITLE
Pharo images can crash after sleep of OSX

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-vm#72]
Ported from https://github.com/pharo-project/pharo/issues/2422

> It happens to me a lot when I launch my computer that was in sleep mode that a Pharo image crashes on OSX.
> 
> This is really annoying because I lose some code and on top of that I don't know which image it was.
> 
> Related subject: http://forum.world.st/Pharo-7-crashes-on-OSX-when-unsuspending-laptop-td5095115.html
>

**Comment by guillep** [comment]
We need to see if this is fixed by the headless VM

**Comment by chisandrei** [comment]
@guillep I've been using only the headless vm for the past months and I don't remember having those crashes any more; with the non-headless vm they were happening a lot

**Comment by bencoman** [comment]
Not completely sure its the right code, but to review other applications experiencing the same, 
searching for: `osx application crash after sleep "can't allocate region securely"`
turned up this (refer fourth last line)...
https://opensource.apple.com/source/libmalloc/libmalloc-116.50.8/src/magazine_malloc.c.auto.html
```
allocate_pages_securely(szone_t *szone, size_t size, unsigned char align, int vm_page_label)
{
	mach_vm_address_t vm_addr;
	uintptr_t addr;
	mach_vm_size_t allocation_size = round_page_quanta(size);
	mach_vm_offset_t allocation_mask = ((mach_vm_offset_t)1 << align) - 1;
	int alloc_flags = VM_FLAGS_ANYWHERE | VM_MAKE_TAG(vm_page_label);
	kern_return_t kr;

	if (szone->debug_flags & DISABLE_ASLR) {
		return allocate_pages(szone, size, align, 0, vm_page_label);
	}

	if (!allocation_size) {
		allocation_size = vm_page_quanta_size;
	}
	if (allocation_size < size) { // size_t arithmetic wrapped!
		return NULL;
	}

retry:
	vm_addr = entropic_address;
	kr = mach_vm_map(mach_task_self(), &vm_addr, allocation_size, allocation_mask, 
                        alloc_flags, MEMORY_OBJECT_NULL, 0, FALSE,
			VM_PROT_DEFAULT, VM_PROT_ALL, VM_INHERIT_DEFAULT);
	if (kr == KERN_NO_SPACE) {
		vm_addr = vm_page_quanta_size;
		kr = mach_vm_map(mach_task_self(), &vm_addr, allocation_size, allocation_mask,
                              alloc_flags, MEMORY_OBJECT_NULL, 0, FALSE,
			      VM_PROT_DEFAULT, VM_PROT_ALL, VM_INHERIT_DEFAULT);
	}
	if (kr) {
		szone_error(
		      szone, 0, "can't allocate region securely", NULL, 
                      "*** mach_vm_map(size=%lu) failed (error code=%d)\n", size, kr);
		return NULL;
	}
```

**Comment by bencoman** [comment]
[Firefox hangs on wake up from OS X Power Nap r=spohl](https://hg.mozilla.org/releases/mozilla-release/rev/5ad3201e605e4fb3c18b3603d6b560b8b7e10ea2) is interesting, since Pharo has multiple threads.  Could any of them continue to run as a Power Nap app while a laptop is sleeping?
(btw, It talks about processes but IIUC OSX only has threads not processes.)

**Comment by bencoman** [comment]
I notice [this](https://fmpexperts.ironclad.net.narkive.com/9YCK9YvW/fmp-12-crashing-during-window-intensive-operations-on-os-x-10-9-2)
> FileMaker has accepted negative window coordinates for me in OS X for years. I just tried in 13 on Mountain Lion, I opened an 800x800 window at -1000x-1000, it was fully off screen and behaved as expected (responded to command-W).

Probably unrelated, but it does produce the same error message.

**Comment by bencoman** [comment]
A situation that [can happen when returning from fullscreen Space on shutdown](https://hg.libsdl.org/SDL/rev/b93491afe676) is interesting.

**Comment by bencoman** [comment]
Sorry I don't have a specific reference, but after a lot of browsing stewing in my mind, I wonder if during the laptop-sleep some graphics buffer is being discarded deep in the OS, and its not valid when Pharo references it.  I wonder if the the vm should catch laptop-wakeup events (if thats possible) and hide-then-restore the Pharo window.

**Comment by bencoman** [comment]
Summarized C backtrace....
```
Pharo(67603,0xa983a1c0) malloc: 
*** mach_vm_map(size=8388608) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
Segmentation fault Tue Feb 12 17:31:59 2019
0  libobjc.A.dylib ............ GLOBAL__N_119 AutoreleasePoolPage........
1  ..........
2  ..........
3  ..........
4  ..........
5  libobjc.A.dylib .......... AutoreleasePoolPage19autoreleaseFullPage ..........
6  libobjc.A.dylib .......... objc_object16rootAutorelease2Ev
7  libobjc.A.dylib .......... objc_loadWeak 
8  AppKit .......... [NSEvent window]
9  AppKit .......... nextEventMatchingEventMask:untilDate:inMode:dequeue:
10 AppKit .......... nextEventMatchingMask:untilDate:inMode:dequeue:
11 Pharo  .......... pumpRunLoopEventSendAndSignal:
```

**Comment by seandenigris** [comment]
Just happened to me.

**Describe the bug**
When I woke my MBP 2018 up from sleep, Launcher had crashed (VM). This seems to be intermittent because I've woken my Mac up from sleep many times but this never happened before.

**To Reproduce**
1. Put Mac to sleep
2. Wake it up

**Version information:**
 - OS: 10.14.6
 - Version: Pharo-9.0.0+build.345.sha.1604382b75d9ef6dd755473fa4262e087ad4ba05 (64 Bit)

**Expected development cost**
?

**Additional context**
[crash.dmp.txt](https://github.com/pharo-project/opensmalltalk-vm/files/4753019/crash.dmp.txt)

**Comment by ainthek** [comment]
2024 - Just installed latest Pharo Laucher PharoLauncher-3.2-x64.dmg, and my MacBook Pro 2023 with OSX 14.4.1 crashed two times. One just after 1st launch. 2nd time when clicking on New Image. Renders whole think useless. (sorry for no help) but searching issues I have not found any usefull information.

**Comment by guillep** [comment]
Hi @ainthek , is it the pharo launcher that crashed? Was it after MacOS went to sleep?

**Comment by ainthek** [comment]
no it crashed without going to sleep.

**Comment by guillep** [comment]
We had reports of a lot of users having problems with MacOS 14.4.1, but some of the reports acknowledged that it was not only Pharo causing problems.

@jordanmontt recently upgraded to 14.5 and all those problems got solved.

**Comment by guillep** [comment]
I propose to close this issue. The original issue is not there anymore, the new architecture solves the problems originally posted.

@ainthek , please, try to update your OS, if the problem persists, I invite you to open another issue with a proper description.
Also, you may found crash dump files next to the image file that could help us debugging.
