### ISSUE TITLE
VM breaks Pharo integration into Mac Os [menu bar]

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-vm#735]
Hi,

Current Pharo VM has a really strange behavior with the app menu bar.
When Pharo VM is active, either it shows an empty menu bar either it show the menu bar from the previously selected app.

![Capture d’écran 2024-02-07 à 08 58 15](https://github.com/pharo-project/pharo-vm/assets/2494203/28a382ba-56c1-40dc-a6ad-c0456e96f72d)

When the menu is hidden, we even lose the clock, the battery and networks indicators, etc.
![Capture d’écran 2024-02-07 à 09 15 53](https://github.com/pharo-project/pharo-vm/assets/2494203/fef92de9-ebe0-417b-b2aa-c807d683345a)

Reported from Mac Os 14.3

**Comment by Rinzwind** [comment]
Related issue: https://github.com/pharo-project/pharo/issues/15564

**Comment by tesonep** [comment]
Fixed in the image
