### ISSUE TITLE
Problem with completion in the tutorial

### ISSUE THREAD

**Issue by jacereda** [pharo-project/pharo-vm#796]
I've finished packaging the latest release for Guix, but looks like there's a problem with the tutorial. In the first tutorial step, just type `ProfStef n` and it should trigger the problem.

![image](https://github.com/pharo-project/pharo-vm/assets/4195919/f3c45a57-5a53-46c4-ba05-42ce5186f7f6)

**Comment by jacereda** [comment]
Maybe it's just a problem on my side. This is how I invoked it:

```pharo ~/Downloads/Pharo12.0-SNAPSHOT-64bit-c19563f.image --interactive```

And now I realize this is probably the wrong repo. Should I open it in https://github.com/pharo-project/pharo ?

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">GitHub - pharo-project/pharo: Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk.</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>

**Comment by jordanmontt** [comment]
Yes, please open it in the Pharo repo, This one if for the VM

**Comment by jacereda** [comment]
https://github.com/pharo-project/pharo/issues/16576
