### ISSUE TITLE
please keep versioned files for Pharo 12 at http://files.pharo.org/vm/pharo-spur64-headless/Linux-x86_64/source/

### ISSUE THREAD

**Issue by Dieken** [pharo-project/pharo-vm#865]
I'm fixing FreeBSD ports lang/pharo: https://github.com/freebsd/freebsd-ports/pull/320,  originally Pharo uploaded versioned files for Pharo 10, that's good practice, but Pharo 12 has only a `latest12.zip` and a `latest12.tar.gz`,  that's bad for reproducible build.

Please keep versioned files for Pharo 12 too at http://files.pharo.org/vm/pharo-spur64-headless/Linux-x86_64/source/ .

**Comment by Dieken** [comment]
any feedback?

**Comment by guillep** [comment]
Hi @Dieken the versioning of the VM is independent of the "shown" Pharo version.
Right now, the latest VM 10.x release (10.3.1) is used in production for Pharo 10 through 13.

So there is no source code package because there is VM version 12 :)

**Comment by Dieken** [comment]
Get it, thanks for your clarification!
